name: Deploy to CurseForge

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Package and publish
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CURSEFORGE_API_TOKEN }}
